# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-01 17:13
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0002_expensedetail_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callfunds',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'building'), (1, 'valid'), (2, 'ended')], db_index=True, default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'building'), (1, 'valid'), (2, 'ended')], db_index=True, default=0, verbose_name='status'),
        ),
        migrations.AlterModelOptions(
            name='partition',
            options={'default_permissions': [], 'ordering': ['owner__third_id', 'set_id'], 'verbose_name': 'partition', 'verbose_name_plural': 'partitions'},
        ),
    ]
