# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-27 11:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0003_callfunds_expense_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1, verbose_name='numeros')),
                ('value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='value')),
                ('description', models.TextField(default='', null=True, verbose_name='description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominium.Owner', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'property lot',
                'ordering': ['num'],
                'verbose_name_plural': 'property lots',
                'default_permissions': [],
            },
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'verbose_name': 'class load', 'verbose_name_plural': 'class loads'},
        ),
    ]
