# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-27 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0004_propertylot'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='set',
            name='is_link_to_lots',
            field=models.BooleanField(default=False, verbose_name='is link to lots'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_of_lots',
            field=models.ManyToManyField(blank=True, to='condominium.PropertyLot', verbose_name='set of lots'),
        ),
        migrations.AddField(
            model_name='set',
            name='type_load',
            field=models.IntegerField(choices=[(0, 'current'), (1, 'exceptional')], db_index=True, default=0, verbose_name='type of load'),
        ),
    ]
