# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-18 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payoff', '0006_depositslip_status'),
        ('condominium', '0006_expenseratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallFundsSupporting',
            fields=[],
            options={
                'default_permissions': [],
            },
            bases=('payoff.supporting',),
        ),
        migrations.AlterModelOptions(
            name='partition',
            options={'default_permissions': [], 'ordering': ['owner__third_id', 'set_id'],
                     'verbose_name': 'class load', 'verbose_name_plural': 'class loads'},
        ),
        migrations.AddField(
            model_name='callfunds',
            name='supporting',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='condominium.CallFundsSupporting'),
        ),
    ]
