# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-27 18:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payoff', '0006_depositslip_status'),
        ('condominium', '0010_exeptional_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partition',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100000.0)], verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='propertylot',
            name='value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='value'),
        ),
    ]
