# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-28 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payoff', '0006_depositslip_status'),
        ('condominium', '0012_ownercontact'),
    ]

    operations = [

    ]
