# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-28 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payoff', '0006_depositslip_status'),
        ('condominium', '0012_ownercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='callfundssupporting',
            name='supporting_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payoff.Supporting'),
            preserve_default=False,
        ),
    ]
