# Generated by Django 2.0.8 on 2018-09-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payoff', '0006_depositslip_status'),
        ('condominium', '0013_callfundssupporting_supporting_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetail',
            name='type_call',
            field=models.IntegerField(choices=[(0, 'current'), (1, 'exceptional'), (2, 'cash advance'), (3, 'borrowing'), (4, 'fund for works')], db_index=True, default=0, verbose_name='type of call'),
        ),
        migrations.AlterField(
            model_name='callfunds',
            name='type_call',
            field=models.IntegerField(db_index=True, default=None, null=True, verbose_name='type of call'),
        ),
    ]
