# Generated by Django 2.0.8 on 2018-09-21 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payoff', '0006_depositslip_status'),
        ('condominium', '0014_callfunds_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callfunds',
            options={'ordering': ['date', 'num'], 'verbose_name': 'call of funds', 'verbose_name_plural': 'calls of funds'},
        ),
        migrations.AlterField(
            model_name='calldetail',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='condominium.Set', verbose_name='set'),
        ),
    ]
