# Generated by Django 3.1.7 on 2021-09-24 08:59

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_fiscalyear_deletecascade'),
        ('condominium', '0017_proxy_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callfunds',
            name='type_call',
            field=models.IntegerField(choices=[], db_index=True, default=None, null=True, verbose_name='type of call'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'building expense'), (3, 'waiting expense'), (1, 'valid expense'), (2, 'ended expense'), (4, 'cancel expense')], db_index=True, default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='setcost',
            name='year',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.fiscalyear', verbose_name='fiscal year'),
        ),
    ]
