# Generated by Django 3.2.14 on 2022-10-21 08:26

import django.core.validators
from django.db import migrations, models
from lucterios.framework.model_fields import LucteriosDecimalField


class Migration(migrations.Migration):

    dependencies = [
        ('payoff', '0011_fiscalyear_deletecascade'),
        ('condominium', '0019_secondary_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylot',
            name='value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000)], verbose_name='general tantime'),
        ),
        migrations.AlterField(
            model_name='propertylotcustomfield',
            name='value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000)], verbose_name='tantime'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='value',
            field=LucteriosDecimalField(decimal_places=2, default=0.0, max_digits=13, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000000000.0)], verbose_name='tantime'),
        ),
    ]
